### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by dastanozgeldi** [EraOfCoding/IA-bot#1]
the program does not work for unix-based systems.

that hurt ma heart :(

**Comment by EraOfCoding** [comment]
That is sad to hear, but there are some possible solutions:
1) Switch to Windows
2) Sell Mac and switch to Windows
Alternatives may be:
1) Sell your Mac device to me and switch to Windows

**Comment by dastanozgeldi** [comment]
Those solution do not seem to help me, anyways thanks!
